from typing import List, Optional, Tuple
from app.data.db import connect_database


def create_user(username: str, password_hash: str, role: str = "user") -> None:
    """
    Insert a new user into the users table.
    The password_hash is already generated by the Week 7 auth system.
    """
    conn = connect_database()
    cur = conn.cursor()
    cur.execute(
        "INSERT INTO users (username, password_hash, role) VALUES (?, ?, ?)",
        (username, password_hash, role),
    )
    conn.commit()
    conn.close()


def get_user_by_username(username: str) -> Optional[Tuple[int, str, str]]:
    """
    Fetch a single user by username.

    Returns a tuple (id, username, role) or None if not found.
    """
    conn = connect_database()
    cur = conn.cursor()
    cur.execute(
        "SELECT id, username, role FROM users WHERE username = ?",
        (username,),
    )
    row = cur.fetchone()
    conn.close()
    return row


def get_all_users() -> List[Tuple[int, str, str]]:
    """
    Return all users as a list of (id, username, role) tuples.
    """
    conn = connect_database()
    cur = conn.cursor()
    cur.execute("SELECT id, username, role FROM users ORDER BY id")
    rows = cur.fetchall()
    conn.close()
    return rows


def update_user_role(username: str, new_role: str) -> int:
    """
    Change the role for a given username.

    Returns the number of rows that were updated (0 or 1).
    """
    conn = connect_database()
    cur = conn.cursor()
    cur.execute(
        "UPDATE users SET role = ? WHERE username = ?",
        (new_role, username),
    )
    conn.commit()
    count = cur.rowcount
    conn.close()
    return count


def delete_user(username: str) -> int:
    """
    Delete a user from the table.

    Returns the number of rows that were deleted (0 or 1).
    """
    conn = connect_database()
    cur = conn.cursor()
    cur.execute(
        "DELETE FROM users WHERE username = ?",
        (username,),
    )
    conn.commit()
    count = cur.rowcount
    conn.close()
    return count
